<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJucxbit\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJucxbit/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJucxbit.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJucxbit\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJucxbit\appProdProjectContainer(array(
    'container.build_hash' => 'Jucxbit',
    'container.build_id' => '00453c25',
    'container.build_time' => 1516491353,
));
