<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAfygn6p\appDevProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAfygn6p/appDevProjectContainer.php') {
    touch(__DIR__.'/ContainerAfygn6p.legacy');

    return;
}

if (!\class_exists(appDevProjectContainer::class, false)) {
    \class_alias(\ContainerAfygn6p\appDevProjectContainer::class, appDevProjectContainer::class, false);
}

return new \ContainerAfygn6p\appDevProjectContainer(array(
    'container.build_hash' => 'Afygn6p',
    'container.build_id' => '6dfd0949',
    'container.build_time' => 1516490825,
));
